export interface AamvaFieldDefinition {
  code: string;
  label: string;
  washingtonLabel?: string;
}

export const AAMVA_FIELD_DEFINITIONS: AamvaFieldDefinition[] = [
  { code: "DAA", label: "Full Name", washingtonLabel: "Full legal name" },
  { code: "DAB", label: "Family Name", washingtonLabel: "Family name" },
  { code: "DAC", label: "Given Name", washingtonLabel: "First name" },
  { code: "DAD", label: "Middle Name", washingtonLabel: "Middle name" },
  { code: "DAE", label: "Name Suffix" },
  { code: "DAF", label: "Name Prefix" },
  { code: "DAG", label: "Mailing Street Address1", washingtonLabel: "Mailing address line 1" },
  { code: "DAH", label: "Mailing Street Address2", washingtonLabel: "Mailing address line 2" },
  { code: "DAI", label: "Mailing City", washingtonLabel: "Mailing city" },
  { code: "DAJ", label: "Mailing Jurisdiction Code (State)", washingtonLabel: "Mailing state (WA)" },
  { code: "DAK", label: "Mailing Postal Code", washingtonLabel: "Mailing ZIP" },
  { code: "DAL", label: "Residence Street Address1" },
  { code: "DAM", label: "Residence Street Address2" },
  { code: "DAN", label: "Residence City" },
  { code: "DAO", label: "Residence Jurisdiction Code" },
  { code: "DAP", label: "Residence Postal Code" },
  { code: "DAQ", label: "License or ID Number", washingtonLabel: "Washington license or ID number" },
  { code: "DAR", label: "License Classification Code", washingtonLabel: "Washington class code" },
  { code: "DAS", label: "License Restriction Code", washingtonLabel: "Washington restrictions" },
  { code: "DAT", label: "License Endorsements Code", washingtonLabel: "Washington endorsements" },
  { code: "DAU", label: "Height in FT_IN" },
  { code: "DAV", label: "Height in CM" },
  { code: "DAW", label: "Weight in LBS" },
  { code: "DAX", label: "Weight in KG" },
  { code: "DAY", label: "Eye Color" },
  { code: "DAZ", label: "Hair Color" },
  { code: "DBA", label: "License Expiration Date" },
  { code: "DBB", label: "Date of Birth" },
  { code: "DBC", label: "Sex" },
  { code: "DBD", label: "License or ID Document Issue Date" },
  { code: "DBE", label: "Issue Timestamp" },
  { code: "DBF", label: "Number of Duplicates" },
  { code: "DBG", label: "Medical Indicator Codes" },
  { code: "DBH", label: "Organ Donor" },
  { code: "DBI", label: "Non-Resident Indicator" },
  { code: "DBJ", label: "Unique Customer Identifier" },
  { code: "DBK", label: "Social Security Number" },
  { code: "DBL", label: "Date of Birth" },
  { code: "DBM", label: "Social Security Number" },
  { code: "DBN", label: "Full Name" },
  { code: "DBO", label: "Family Name" },
  { code: "DBP", label: "Given Name" },
  { code: "DBQ", label: "Middle Name or Initial" },
  { code: "DBR", label: "Suffix" },
  { code: "DBS", label: "Prefix" },
  { code: "DCA", label: "Specific Class", washingtonLabel: "Washington specific class" },
  { code: "DCB", label: "Specific Restrictions", washingtonLabel: "Washington specific restrictions" },
  { code: "DCD", label: "Specific Endorsements", washingtonLabel: "Washington specific endorsements" },
  { code: "DCE", label: "Physical Description Weight Range" },
  { code: "DCF", label: "Document Discriminator" },
  { code: "DCG", label: "Country territory of issuance" },
  { code: "DCH", label: "Federal Commercial Vehicle Codes" },
  { code: "DCI", label: "Place of birth" },
  { code: "DCJ", label: "Audit information" },
  { code: "DCK", label: "Inventory Control Number" },
  { code: "DCL", label: "Race Ethnicity" },
  { code: "DCM", label: "Standard vehicle classification" },
  { code: "DCN", label: "Standard endorsement code" },
  { code: "DCO", label: "Standard restriction code" },
  { code: "DCP", label: "Jurisdiction specific vehicle classification description" },
  { code: "DCQ", label: "Jurisdiction-specific" },
  { code: "DCR", label: "Jurisdiction specific restriction code description" },
  { code: "DCS", label: "Last Name" },
  { code: "DCT", label: "First Name" },
  { code: "DCU", label: "Suffix" },
  { code: "DDA", label: "Compliance Type" },
  { code: "DDB", label: "Card Revision Date" },
  { code: "DDC", label: "HazMat Endorsement Expiry Date" },
  { code: "DDD", label: "Limited Duration Document Indicator" },
  { code: "DDE", label: "Family Name Truncation" },
  { code: "DDF", label: "First Names Truncation" },
  { code: "DDG", label: "Middle Names Truncation" },
  { code: "DDH", label: "Under 18 Until" },
  { code: "DDI", label: "Under 19 Until" },
  { code: "DDJ", label: "Under 21 Until" },
  { code: "DDK", label: "Organ Donor Indicator" },
  { code: "DDL", label: "Veteran Indicator" },
  { code: "PAA", label: "Permit Classification Code" },
  { code: "PAB", label: "Permit Expiration Date" },
  { code: "PAC", label: "Permit Identifier" },
  { code: "PAD", label: "Permit IssueDate" },
  { code: "PAE", label: "Permit Restriction Code" },
  { code: "PAF", label: "Permit Endorsement Code" },
  { code: "ZVA", label: "Court Restriction Code", washingtonLabel: "Washington court restriction" },
  { code: "ZxZ", label: "State Specific fields where x is variable" },
  { code: "Zxx", label: "State Specific fields where xx is variable" },
];

export const AAMVA_FIELD_ORDER = AAMVA_FIELD_DEFINITIONS.map((item) => item.code).filter(
  (code) => !code.includes("x"),
);

export const AAMVA_REQUIRED_CORE_CODES = ["DAQ", "DCS", "DAC", "DBB", "DBA"];

export const AAMVA_WA_DEFAULTS: Record<string, string> = {
  DAJ: "WA",
  DAO: "WA",
  DCG: "USA",
};
